### ISSUE TITLE
Update firmware on switch?

### ISSUE THREAD

**Issue by hesingh** [openconfig/reference#103]
I am wondering if I have to update firmware on a switch that supports gRPC, how would I do that?  I don't see gNMI nor gNOI support such an operation.   I wanted to know if there is any known interface for such a task or does one hack with protobuf with a binary blob of data and also have the switch understand the blob?

**Comment by robshakir** [comment]
Hi,

There is a gNOI RPC for upgrading firmware. Please see the [`SetPackage`](https://github.com/openconfig/gnoi/blob/master/system/system.proto#L48) RPC in system.proto.

Thanks,
r.

**Comment by hesingh** [comment]
Sorry, I think, this repo should not address my question.  I am closing the issue.

**Comment by hesingh** [comment]
Incidentally, since you and others wrote a great IETF draft, for gNMI, please consider writing one for gNOI.
