### ISSUE TITLE
RFC standard for gNMI

### ISSUE THREAD

**Issue by rdpravin1895** [openconfig/reference#131]
Is there a potential possibility of coming up with an RFC for gNMI similar to NETCONF/RESTCONF? Lot of network elements have started incorporating gNMI in their architecture, but it always co-exists with the other management protocols. Also as these protocols are standardized through RFC's, they are being extensively used in the upcoming network technologies like 5G (oRAN alliance and ONAP to be spceific).

I could see an IETF draft available: **https://tools.ietf.org/html/draft-openconfig-rtgwg-gnmi-spec-01**
But it doesn't provide any info other than a high level view. The specification available in Github serves as the fallback.

**Comment by aashaikh** [comment]
In the case of gNMI, the authoritative spec is in Github (i.e., not intended to be a fallback).  We did the draft a while back to provide visibility of the project in IETF without necessarily going through the lengthy standardization process for the spec.

gNMI is widely supported and used at this point across different types of network devices (as you pointed out), and is developed in open source, so it's not clear there is any barrier to adoption for projects like oRAN or ONAP.

**Comment by rdpravin1895** [comment]
@aashaikh My bad. Thanks for clarifying it out. In that case I don't understand why ONAP or oRAN have not taken up gNMI as a management/telemetry interface. Only NETCONF and REST/RESTCONF are being considered.
