### ISSUE TITLE
Can I push CLI commands remotely using gNMI?

### ISSUE THREAD

**Issue by asydney** [openconfig/reference#136]
Hi gNMI folks, 
                       I'm new to gNMI and have only used it for use cases such as subscribing to pkt counters etc. In any case, I'm configuring "SONiC" switches and below are some of the commands executed at the CLI::

"""
sonic> sudo config interface ip remove Ethernet16 10.0.0.8/31
sonic> sudo config interface ip add Ethernet16 10.10.1.2/31
sonic> sudo config interface ip add Loopback0 10.0.1.13/32
sonic> sudo vtysh
sonic> configure t
sonic> no router bgp 65100
sonic> router bgp 65021
sonic> bgp router-id 10.0.1.13
"""

Question:
Given that SONiC has support for gNMI (https://github.com/Azure/SONiC/blob/master/doc/mgmt/Management%20Framework.md#3123-gnmi), cab I push these configurations remotely via gNMI.

Thanks,
-Syd

**Comment by gcsl** [comment]
Yes, gNMI does support config push via the Set RPC which does support mixed-schema configuration, including CLI.  The question as to which OpenConfig models are supported for configuration by SONiC and whether CLI can also be delivered over gNMI should be directed to that project.

**Comment by asydney** [comment]
Will do.

Thanks!
-Syd

**Comment by hellt** [comment]
Hi @gcsl 
I wonder what combination of fields enable mixed-mode for the devices that support it? Is it ASCII typed value?
Otherwise how would the target decide if it needs to consult with the YANG or else?

**Comment by gcsl** [comment]
gNMI is designed to be schema agnostic such that it can transport both OpenConfig and vendor native configuration.  The disambiguation is achieved by the origin field within the path (https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#222-paths).  For OpenConfig models this value should be "openconfig".  For vendor native models, including CLI text, this value and all mixed mode semantics are vendor defined.  The goal for the OpenConfig project, which defines gNMI, is to standardize configuration within OpenConfig models but the use of gNMI does not preclude the use of vendor specific models.

**Comment by robshakir** [comment]
There is some description of how mixed schema in gNMI works in [this doc](https://github.com/openconfig/reference/blob/master/rpc/gnmi/mixed-schema.md).
