### ISSUE TITLE
Must STREAM Subscriptions' responses be in timestamp order?

### ISSUE THREAD

**Issue by wenovus** [openconfig/reference#145]
https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#35152-stream-subscriptions

Sorry I remember this not being guaranteed. Could the spec clarify this?

**Comment by hellt** [comment]
@wenovus @robshakir sorry for necro-posing, but this might not be worth a separate issue

I am trying to understand the constraints aroung Notification Timestamps. If we create a sampled subscription to a leaf that rarely changes (like `/interface/description`), then should a target respond with a TS at which the description leaf changed last (thus TS appears the same in all notifications until changed) or should instead it reflect collection time each time a target queries this leaf internally?
