### ISSUE TITLE
Clarification regarding on-change and initial sync

### ISSUE THREAD

**Issue by amanand** [openconfig/reference#147]
Hi,
I need to understand the collector expectation for GNMI subscriptions with updates_only set to false and subscription mode being ON_CHANGE. Does this mean that only the leafs in the subscribed xpath tree that support notifications should stream out initial sync data and thereafter whenever there is any event? Or does it mean that all the leafs in the subscribed xpath tree irrespective of whether they support notifications or not should stream their initial data once and then thereafter whenever there is any event?
For example: in case of OnChange subscription of /interfaces/, whether initial sync should contain the counter leafs or not?

Thanks
Amish

**Comment by gcsl** [comment]
Sync should be sent after the updates for all leaves regardless of mode are sent when updates_only is false.  Sync indicates that a collector has been delivered the full state of the device.  Yes, counters should be included.
