### ISSUE TITLE
Add rpc for retrieving service version

### ISSUE THREAD

**Issue by aashaikh** [openconfig/reference#15]
We need an rpc (e.g., `GetServiceVersion`) that returns the version of the service to the caller.  To be consistent with the versioning scheme for models, I would suggest to stick with a semantic version number (`major.minor.bugfix`).  We should also add / maintain a service version in the .proto file -- backends would be expected to use this number when implementing this call.

An alternative would be to update the name of the file, e.g., `openconfig_v0_1_1` but it seems a little unwieldy to keep all of these versions checked in as different names.

This request is based on asks from vendors using the proto for a way to manage versioning of the service at the "application" layer.

**Comment by robshakir** [comment]
This RPC was included in gNMI as part of the capabilities. We adopted a semantic version in keeping with the other projects that we have.
