### ISSUE TITLE
The Python generated code for `openconfig.proto` cannot find the code for `any.proto`

### ISSUE THREAD

**Issue by 7AC** [openconfig/reference#24]
As part of 8edb7a9ba7d8c58cc7641f21efff197c277f2faa the import of `any.proto` was changed as follows:

``` diff
@@ -15,7 +15,7 @@
 //
 syntax = "proto3";

-import "google/protobuf/any.proto";
+import "github.com/golang/protobuf/ptypes/any/any.proto";

 // Package openconfig defines the gRPC service for getting and setting the
 // configuration and state data of a network target based on OpenConfig models.
```

As a result the relative path doesn't match the one under Python's site dir anymore, resulting in an `ImportError`:

```
Traceback (most recent call last):
  File "./openconfig_client.py", line 16, in <module>
    import pyopenconfig.pb2
  File "/Users/gvalente/src/pyopenconfig/pyopenconfig/pb2.py", line 17, in <module>
    from github.com.golang.protobuf.ptypes.any import any_pb2 as github_dot_com_dot_golang_dot_protobuf_dot_ptypes_dot_any_dot_any__pb2
ImportError: No module named github.com.golang.protobuf.ptypes.any
```

I could generate the code for `any.proto` and start distributing it under `$sitelib/github/com/golang/protobuf/ptypes` but it doesn't seem very pythonic. What's the recommended way to handle this in Python?

I generated the code with

``` sh
protoc -I .:$GOPATH/src --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` openconfig.proto
```

resulting in:

```
gvalente:openconfig gvalente$ grep "from github.com" openconfig_pb2.py                                                                                                                                                                        
from github.com.golang.protobuf.ptypes.any import any_pb2 as github_dot_com_dot_golang_dot_protobuf_dot_ptypes_dot_any_dot_any__pb2
```

Doing anything else doesn't seem to work, for example copying `any.proto` to `.`:

```
gvalente:openconfig gvalente$ ls -l any.proto 
-rw-r--r--  1 gvalente  staff  5281 Sep 20 17:59 any.proto
gvalente:openconfig gvalente$ protoc -I . --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` openconfig.proto                                                                                                    
github.com/golang/protobuf/ptypes/any/any.proto: File not found.
openconfig.proto: Import "github.com/golang/protobuf/ptypes/any/any.proto" was not found or had errors.
openconfig.proto:376:3: "google.protobuf.Any" is not defined.
```

**Comment by 7AC** [comment]
This seems to work as a workaround:

```bash
sed -i.bak "s/github.com.golang.protobuf.ptypes.any/google.protobuf/" openconfig_pb2.py
sed -i.bak "s/github_dot_com_dot_golang_dot_protobuf_dot_ptypes_dot_any_dot_any__pb2/google_dot_protobuf_dot_any__pb2/" openconfig_pb2.py
```

**Comment by marcushines** [comment]
I am following up as with the grpc team to see about a language agnostic
way to handle this

On Sep 20, 2016 11:26 PM, "Giuseppe Valente" <notifications@github.com>
wrote:

This seems to work as a workaround:

sed -i.bak "s/github.com.golang.protobuf.ptypes.any/google.protobuf/"
openconfig_pb2.py
sed -i.bak "s/github_dot_com_dot_golang_dot_protobuf_dot_ptypes_dot_any_dot_any__pb2/google_dot_protobuf_dot_any__pb2/"
openconfig_pb2.py

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openconfig/reference/issues/24#issuecomment-248522792>,
or mute the thread

**Comment by robshakir** [comment]
Closing this issue as historical, I believe this was resolved for `gnmi.proto` in the [openconfig/gnmi](https://github.com/openconfig/gnmi) repo.
