### ISSUE TITLE
gNMI Specification Encoding Enum Inconsistencies

### ISSUE THREAD

**Issue by aaronbee** [openconfig/reference#32]
The table in section 2.2.3 of the gnmi-specification does not match gnmi.proto. Specifically, ASCII and JSON_IETF have reversed values.

Also, the link to the ASCII section is broken.

Also, section 2.3.4 uses `TEXT` instead of `ASCII`.

**Comment by robshakir** [comment]
Hi Aaron,

Thanks - I'll fix these and push a new version.

Cheers,
r.

**Comment by robshakir** [comment]
This was fixed in v0.2.1.
