### ISSUE TITLE
gNMI Specification: using Unimplemented instead of InvalidArgument for unsupported encodings

### ISSUE THREAD

**Issue by tsuna** [openconfig/reference#36]
This is a bit of a detail but since the spec specifies explicitly what to do in this case...  From Section 3.3.1 (The GetRequest Message):

> If the target does not support the specified encoding, the target MUST populate the error field of the `GetResponse` message, specifying an error of `InvalidArgument`.

`InvalidArgument` is for malformed input, but here if a client requests `JSON_IETF` encoding and the target doesn't support it, the request isn't malformed, it's just asking for something that is not supported by the target's implementation.

From https://godoc.org/google.golang.org/grpc/codes#Code

```go
    // InvalidArgument indicates client specified an invalid argument.
    // Note that this differs from FailedPrecondition. It indicates arguments
    // that are problematic regardless of the state of the system
    // (e.g., a malformed file name).
    InvalidArgument Code = 3
```
vs

```go
    // Unimplemented indicates operation is not implemented or not
    // supported/enabled in this service.
    Unimplemented Code = 12
```

There may be other instances of this issue in the spec.

**Comment by tsuna** [comment]
In the same vein, I find this (in Section 3.4.7 [Error Handling]) a bit weird:

> When the operation is an update or replace operation that corresponds to a path that is not valid - `NotFound (5)`.

This seems inconsistent with Section 3.4.4 (Modes of Update: Replace versus Update):

> For both replace and update operations, if the path specified does not exist, the target MUST create the data tree element and populate it with the data in the `Update` message

If the path is not valid, I would imagine that `InvalidArgument` should be returned instead of `NotFound`.

**Comment by tsuna** [comment]
Another instance of the problem mentioned in my first message is in Section 3.4.7 as well:

> _[...]_ `InvalidArgument (3)`. This error SHOULD be used _[...]_ in the case that multiple values are specified using a particular encoding (e.g., JSON) which cannot be decoded by the target.

Here I believe `Unimplemented` should be used instead.

**Comment by robshakir** [comment]
I tend to agree here - in both cases. Particularly, the `Unimplemented` error is more explicit, I'll send a PR to adjust the specification to state this.

**Comment by robshakir** [comment]
Closing this issue as it was resolved some time ago.
