### ISSUE TITLE
encoding the root node

### ISSUE THREAD

**Issue by wisotzky** [openconfig/reference#50]
The latest available version of gnmi specification (v0.2.2) is specifying the following:
The root node (/) is indicated by encoding a single path element which is an empty string

While in the gnmi path conventions (Feb 2017) the root path is defined as zero length list.

So need clearly to define if the root node is encoded as [] or [""] using python syntax.

Little remark:
The release date in the gnmi path conventions is Feb 2016 - but should be Feb 2017.

**Comment by robshakir** [comment]
Hi,

The root node is encoded as `[]` in Python, the latter document is correct. We're just working on updating the document to cover the changes in 0.3.1.

Thanks,
r.

**Comment by wisotzky** [comment]
@robshakir 
I have contributed my gNMI Subscribe() client in Python under MIT license:
https://github.com/nokia/pygnmi

Scope of work is the current Nokia SR OS implementation for the gNMI-based Telemetry interface.
