### ISSUE TITLE
telemetry persistent subscription to configure collector server

### ISSUE THREAD

**Issue by mberroug** [openconfig/reference#58]
There is  no way to define a collector server using current "[gnmi.proto](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi.proto)" Subscribe definition.
Is is ongoing or I should use a Set operation on  [openconfig-telemetry.yang ](https://github.com/openconfig/public/blob/master/release/models/telemetry/openconfig-telemetry.yang)model  to update permanent telemetry data ?

Regards,

**Comment by robshakir** [comment]
Currently, gNMI defines a "dial in" model. This means that the gNMI client specifies to the target the set of subscription paths that it would like to receive dynamically. There is a proposal for a dial-out model whereby the target calls the client which is discussed in #42 -- which we're still discussing.

A model that we currently haven't seen any demand for is the preconfigured subscriptions that are then dial-in. Is this something that you see as required?

**Comment by robshakir** [comment]
More discussion of dial-in requirements has been ongoing for some time, with a discussion that the `openconfig-telemetry` model could be updated for device-configuration-specified subscription paths. There was some discussion of this approach in the `grpctunnel` design document that was shared with the community.

If there are changes to the subscription sets that are required in the `openconfig-telemetry` model, please feel free to make a contribution in the [openconfig/public](https://github.com/openconfig/public) repo.
