### ISSUE TITLE
Path to leaf-list element

### ISSUE THREAD

**Issue by seamusarista** [openconfig/reference#66]
Has a gNMI path to leaf-list elements been considered? I can see it's not too useful to do a Get on a leaf list element. But what would the path look like to Delete a leaf list element? Or suppose there is a subscription to a leaf-list and an element is added what path would be used in the Subscribe Response?

**Comment by gcsl** [comment]
A leaf-list is an opaque value with regard to the path.  There is no way to
delete an individual element and a delete or addition to the list would be
achieved by replacing the value of the leaf-list with a new leaf-list.  The
whole list can be removed by deleting the path to the list.

**Comment by robshakir** [comment]
Agree with Carl, please re-open this issue if further clarification is required.
