### ISSUE TITLE
Migrate gnmi.proto to gnmi repo

### ISSUE THREAD

**Issue by aashaikh** [openconfig/reference#69]
Since we've now created the [gnmi repository](https://github.com/openconfig/gnmi), we are planning to move the `gnmi.proto` service definition and associated files to that repo.   The documentation (protocol spec, etc.) will stay in the `reference` repo for now.

Any automation that pulls `gnmi.proto` from this repo will need to be updated to point to the `gnmi` repo.

**Comment by robshakir** [comment]
Closing this issue off as the migration was done a while ago.
