### ISSUE TITLE
Clarification regarding the newly added "updates_only" field in the SubscribeRequest message

### ISSUE THREAD

**Issue by melgendy-ciena** [openconfig/reference#82]
Hi,
Is the "updates_only" field in the SubscribeRequest message meant for sending "delta" only instead of "absolute" values of the current state, or is it about the initial synchronization during the Subscription not to send the current state at that time, and just keep sending updates in the state after that as per the subscription type?
Thanks..

**Comment by gcsl** [comment]
The "updates_only" does not change the values that are delivered for the
updates.  Counters would still be absolute. This mechanism is used to skip
the synchronization phase and is useful in the context of event-driven
telemetry where a client might only be interested in receiving updates when
changes occur.

A couple example use cases:
- Subscribe to the configuration paths with "updates_only", push a
configuration, record the delay with which changes are reflected back over
telemetry
- Subscribe to RIB with "updates_only", track how much churn is occurring

**Comment by melgendy-ciena** [comment]
Thanks Carl..
