### ISSUE TITLE
GNMI Mutual Authentication

### ISSUE THREAD

**Issue by abhinava** [openconfig/reference#85]
The [spec](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-authentication.md#requirements-on-the-network-device-gnmi-target) mentions that both the client and target mutually authenticate each other. Additionally, it seems to me that TLS client authentication is desirable (or, is it required?).

Would it be okay to skip TLS client authentication? (and just perform username/password based client authentication)

**Comment by robshakir** [comment]
I think this is dependent upon your implementation's requirements. We consider mutual certificate authentication to be the ideal end state for the gNMI protocol - but different users of the protocol might have different requirements at particular times. There are (of course) a number of degrees of implementation flexibility in the spec, and this is one :-)

I'd suggest discussion with your primary consumers to see if this is a MUST for them.
