### ISSUE TITLE
What is motivation of gNMI ? 

### ISSUE THREAD

**Issue by medha-joshi** [openconfig/reference#95]
I want to understand more about :

What motivation or rationale behind gNMI. I can do all types of operations (sync, async, streaming) using gRPC server/client. Can you pl. point out the material ?

Thanks,

Medha

**Comment by gcsl** [comment]
Outlined in the specification.
https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
Additional reference material linked at http://openconfig.net
